version: 0.2

env:
  variables:
    TF_VERSION: "1.3.7"
    DEFAULT_PATH: "/tmp/aft"
    TF_DISTRIBUTION: "oss"
  parameter-store:
    TF_BACKEND_REGION: "/aft/config/oss-backend/primary-region"
    TF_KMS_KEY_ID: "/aft/config/oss-backend/kms-key-id"
    TF_DDB_TABLE: "/aft/config/oss-backend/table-id"
    TF_S3_BUCKET: "/aft/config/oss-backend/bucket-id"
    AFT_ADMIN_ROLE_ARN: "/aft/config/aft-role-arn"

phases:
  pre_build:
    commands:
      # Your existing pre-build commands...
      - echo "Setting up Terraform backend configuration..."
      - |
        cat << EOF > backend.tf
        terraform {
          backend "s3" {
            bucket         = "${TF_S3_BUCKET}"
            key            = "account-request/terraform.tfstate"
            region         = "${TF_BACKEND_REGION}"
            dynamodb_table = "${TF_DDB_TABLE}"
            kms_key_id     = "${TF_KMS_KEY_ID}"
            encrypt        = true
          }
        }
        EOF
      
      # Create terraform.tfvars file
      - |
        cat << EOF > terraform.tfvars
        aft_admin_role_arn = "${AFT_ADMIN_ROLE_ARN}"
        EOF

  build:
    commands:
      - |
        if [ $TF_DISTRIBUTION = "oss" ]; then
          echo "Initializing Terraform..."
          terraform init -no-color
          
          echo "Applying Terraform configuration..."
          terraform apply -no-color --auto-approve -var-file=terraform.tfvars
        fi

  post_build:
    commands:
      - echo "Post-Build"
